voreForArtwork:
  handler: src/rest/vote/voteForArtworks/post.handler
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:UpdateItem
      Resource:
        - Fn::GetAtt: [ votePagesTable, Arn ]
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource:
        - Fn::GetAtt: [ userInfoTable, Arn ]
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - Fn::GetAtt: [ periodTable, Arn ]
  events:
    - http:
        path: vote/voteForArtworks
        authorizer: 
          name: BlckBookUsersAuthorizer
          type: COGNITO_USER_POOLS
          arn:
            Fn::GetAtt:
              - BlckBookUsers
              - Arn
        method: post
        cors: true