// generated by @ng-toolkit/serverless
import 'zone.js/dist/zone-node';
import 'reflect-metadata';

import * as express from 'express';
import * as cors from 'cors';
import * as compression from 'compression';

import { join } from 'path';

export const app = express.default();

const router = express.Router();

router.use(compression.default());
router.use(cors.default());

const DIST_FOLDER = join(process.cwd(), 'dist/blckbook-ui');

router.use(express.static(DIST_FOLDER))

router.get("/*", function (req, res) {
    res.sendFile(join(DIST_FOLDER + '/index.html'));
});

app.use(router)