adminUpdateUploadedArtwork:
  handler: src/rest/artwork/admin/updateUploadedArtwork/post.handler
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - Fn::GetAtt: [ uploadedArtworkTable, Arn ]
  events:
    - http:
        path: artwork/admin/updateUploadedArtwork
        authorizer: 
          name: BlckBookUsersAuthorizer
          type: COGNITO_USER_POOLS
          arn:
            Fn::GetAtt:
              - BlckBookUsers
              - Arn
        method: post
        cors: true