getCurrentPeriod:
  handler: src/rest/period/getCurrentPeriod/get.handler
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - Fn::GetAtt: [ periodTable, Arn ]
  events:
    - http:
        path: period/getCurrentPeriod
        method: get
        cors: true