// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2021-09-14T09:52:24.476Z

interface IAWSAmplifyFederatedConfiguration {
    google_client_id?: string;
    facebook_app_id?: string;
    amazon_client_id?: string;
}

interface IAWSAmplifyCloudLogicConfiguration {
    [index: number]: {
        endpoint: string;
        name: string;
        region: string;
    };
}

interface IAWSAmplifyConfiguration {
    aws_appsync_authenticationType?: string;
    aws_appsync_graphqlEndpoint?: string;
    aws_appsync_region?: string;
    aws_cognito_identity_pool_id?: string;
    aws_cognito_region?: string;
    aws_cloud_logic_custom?: IAWSAmplifyCloudLogicConfiguration;
    aws_project_region: string;
    aws_user_files_s3_bucket?: string;
    aws_user_files_s3_bucket_region?: string;
    aws_user_pools_id?: string;
    aws_user_pools_web_client_id?: string;
    aws_user_pools_web_client_secret?: string;
    federated?: IAWSAmplifyFederatedConfiguration;
}

const awsmobile: IAWSAmplifyConfiguration = {
    aws_cloud_logic_custom: [
        {
            endpoint: 'https://dcp9b1hgg6.execute-api.eu-west-1.amazonaws.com/dev',
            name: 'ApiGatewayRestApi',
            region: 'eu-west-1'
        }
    ],
    aws_cognito_identity_pool_id: 'eu-west-1:eee88de4-7628-4dfb-ba3e-a224d24919a1',
    aws_cognito_region: 'eu-west-1',
    aws_project_region: 'eu-west-1',
    aws_user_pools_id: 'eu-west-1_TdHuFzGxz',
    aws_user_pools_web_client_id: '5d36r2l6irr1k3o19m3dhdr5vm'
};

export default awsmobile;
